repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-toml
      - id: check-yaml
      - id: mixed-line-ending
        args: ["--fix=lf"]
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: debug-statements
      - id: detect-private-key
      - id: fix-encoding-pragma
        args: ["--remove"]

  - repo: local
    hooks:
      - id: black
        name: black
        entry: uv run hatch run dev:format
        language: system
        types: [python]
        pass_filenames: false

      - id: lint
        name: lint
        entry: uv run hatch run dev:lint
        language: system
        types: [python]
        pass_filenames: false

      - id: test
        name: test
        entry: uv run hatch run dev:test
        language: system
        types: [python]
        pass_filenames: false
