name: Quality

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, ready_for_review, auto_merge_enabled]

jobs:
  QualitChecks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.11"]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Hatch
        uses: pypa/hatch@install

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install uv
          uv pip install -e ".[dev]"

      - name: Run Formatter
        run: hatch run dev:format

      - name: Run Quality Checks
        run: hatch run dev:lint

      - name: Run Tests with Coverage
        run: |
          hatch run dev:cov
          hatch run dev:cov-report

      - name: Upload Coverage Results
        uses: actions/upload-artifact@v4
        with:
          name: coverage-results-${{ matrix.python-version }}
          path: htmlcov
        if: ${{ always() }}
