name: Publish

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

on:
  release:
    types: [created]
  workflow_call:
    secrets:
      PYPI_TOKEN:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Publish to PyPI
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Install Hatch
        run: pip install hatch

      - name: Set Version
        run: |
          VERSION=$(git describe --tags --abbrev=0)
          echo "Publishing version $VERSION"
          hatch version $VERSION

      - name: Build and Publish
        env:
          HATCH_INDEX_USER: __token__
          HATCH_INDEX_AUTH: ${{ secrets.PYPI_TOKEN }}
        run: |
          hatch build
          hatch publish
